apiVersion: v1
kind: Pod
metadata:
  labels:
    app: web
  name: redis-django
spec:
  containers:
  - image: redis
    name: key-value-store
    ports:
    - containerPort: 6379
    resources:
      limits:
        cpu: 400m
        ephemeral-storage: 3Gi
        memory: 400Mi
      requests:
        cpu: 200m
        ephemeral-storage: 2Gi
        memory: 200Mi
  - image: django
    name: frontend
    ports:
    - containerPort: 8000
    resources:
      limits:
        cpu: 200m
        ephemeral-storage: 2Gi
        memory: 200Mi
      requests:
        cpu: 100m
        ephemeral-storage: 1Gi
        memory: 100Mi
  nodeName: '7080047917489969872'
